### ISSUE TITLE
alias support from tsconfig

### ISSUE THREAD

**Issue by pi0** [unjs/unbuild#1]

**Comment by lewebsimple** [comment]
Would this feature allow importing from `#app` (i.e. defineNuxtPlugin, useState, etc) inside a Nuxt module built with unbuild ?
Or is this already possible with unbuild ?

**Comment by pi0** [comment]
You should never import from `#app` in a nuxt module

**Comment by lewebsimple** [comment]
How about importing from #app inside a plugin template in a Nuxt module ?

**Comment by pi0** [comment]
Sure that is possible but for runtime files like plugins, we use mkdist that transpiles them file-by-file and without resolving aliases. (see [this example](https://github.com/nuxt/framework/blob/main/packages/nuxt3/build.config.ts#L10))

I will add a better starter template soon. Sorry for lack of it at the moment!

**Comment by pi0** [comment]
Thinking more, using tsConfig with side effects is not the best idea to infer aliases. Using `build.config` seems best.
