### ISSUE TITLE
How to get minify code?

### ISSUE THREAD

**Issue by xieyezi** [unjs/unbuild#112]
I want get minify code after build , and my unbuild config this: 
```ts
import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  entries: ["./index"],
  declaration: true,
  clean: true,
  failOnWarn: false,
  rollup: {
    emitCJS: true,
    esbuild: {
      minify: true
    }
  }
});
```
But after  `pnpm build` , I get this error: 
```shell
Error building E:/project/changan-incall/packages/microApp: Error: Transform failed with 1 error:
<stdin>:1:10: ERROR: Expected ";" but found "EnterMicroAppParams"
Error: Transform failed with 1 error:
<stdin>:1:10: ERROR: Expected ";" but found "EnterMicroAppParams"
    at failureErrorWithLog (E:\project\changan-incall\node_modules\.pnpm\esbuild@0.15.6\node_modules\esbuild\lib\main.js:1624:15)
    at E:\project\changan-incall\node_modules\.pnpm\esbuild@0.15.6\node_modules\esbuild\lib\main.js:1413:29
    at E:\project\changan-incall\node_modules\.pnpm\esbuild@0.15.6\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (E:\project\changan-incall\node_modules\.pnpm\esbuild@0.15.6\node_modules\esbuild\lib\main.js:775:9)
    at Socket.readFromStdout (E:\project\changan-incall\node_modules\.pnpm\esbuild@0.15.6\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Expected ";" but found "EnterMicroAppParams"'
    }
  ],
  warnings: [],
  code: 'PLUGIN_ERROR',
  plugin: 'esbuild',
  hook: 'renderChunk'
}
```
How Can I resolve this ? Hope get you help genuine.

**Comment by xieyezi** [comment]
When I config like this: 
```ts
import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  entries: ["./index"],
  // declaration: true,
  clean: true,
  failOnWarn: false,
  rollup: {
    emitCJS: true,
    esbuild: {
      minify: true
    }
  }
});
```
It's work fine, But can not generate `.d.ts` file , is there any Problem with `declaration` option ?

**Comment by Phl3bas** [comment]
ive also been getting this issue.

to help ive created a minimum reproduction of the bug for anyone looking into this.

min reproduction: https://github.com/Phl3bas/minrepro-unbuild-minify-with-typescript

im assuming this is a bug somewhere with the integration of `rollup-plugin-dts` and/or `rollup-plugin-esbuild`?

same as above removing delarations, builds the file, but without the types, and removing minify builds the types but obviously without minifying the files, having both crashes the build with `ERROR: Expected ";" but found XXXXX`

**Comment by dwightjack** [comment]
I guess @Phl3bas is correct. `rollup-plugin-dts ` doesn't seem to work well with the [esbuild plugin used in unbuild](https://github.com/unjs/unbuild/blob/main/src/builder/plugins/esbuild.ts). For what I can understand, the esbuild plugin tries to load and minify `.d.ts` file chunks generated by the `dts` plugin with the `js` loader ([source](https://github.com/unjs/unbuild/blob/d2cba254232ccb7c411685022598565e49ee36ef/src/builder/plugins/esbuild.ts#L101-L104)) which causes an error because the generated TS definition is not valid JavaScript:

```ts
declare function sum(a: number, b: number): number;
//      ^--- esbuild breaks here
```

unbuild runs two rollup builds, one to transform the source to JS and one (optional) to generate the TS definitions.
I managed to fix the issue using the `rollup:dts:options` hook which receives the option passed to the TS definitions build:

```ts
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  entries: [
    'src/index',
  ],
  declaration: true,
  clean: true,
  rollup: {
    emitCJS: true,
    esbuild: {
        minify: true,
        target: 'es2015',
    }
  },
  hooks: {
    'rollup:dts:options'(_ctx, options) {
    
      if (Array.isArray(options.plugins)) {
        // find the esbuild plugin instance
        const esbuildPlugin = options.plugins.find((p) => (p as any).name === 'esbuild');
        // renderChunk is where the minification happens
        // but we don't want it to be executed
        // on the TS declaration build 
        (esbuildPlugin as any).renderChunk = () => null
      }
    }
  }
})
``` 

This is more of a hack than a workaround, so I guess we should fix the issue with a PR.

**Comment by xieyezi** [comment]
@dwightjack thanks reply, I also found `rollup-plugin-dts` case this error. Maybe we need a PR to  `rollup-plugin-dts`  fix it.

**Comment by jrson83** [comment]
I have the same issue when enabling `minify`.

**Comment by dwightjack** [comment]
I submitted a quick PR that should fix this issue: https://github.com/unjs/unbuild/pull/185
