### ISSUE TITLE
Stub building doesnt work

### ISSUE THREAD

**Issue by Intevel** [unjs/unbuild#114]
I don't know if it's a bug, I think it's a bug on my side, it was working a few hours ago but I don't know what change could have caused it.

The passive watcher does not build correctly, see pictures:

This is my dist output after `unbuild --stub`
![image](https://user-images.githubusercontent.com/59223342/188507447-00553845-4bf2-439f-9117-2beab54b501a.png)

And my build config looks like this:
![image](https://user-images.githubusercontent.com/59223342/188507488-d5f550bd-8201-42b1-a221-da7f81255bd2.png)

In my package.json are no relevant informations, just a playground. No auto detection

**Comment by pi0** [comment]
Thanks for the reproduction. It is might have been a regression with unbuild (not jiti). Do you remember what was last working unbuild version to compare?

BTW checking code, in your config, when you use trailing slash (like `src/`) for entries, builder is **automatically** set to mkdist:

```js
export default {
  entries: [
    "./src/index",
    { input: "src/public/", outDir: "dist/public/" },
    { input: "src/routes/", outDir: "dist/routes/" }
  ]
};
```

(not that I've moved `public/` and `routes/` to the public. It is expected structure to make `src/` and `dist` as identical as possible.

**Comment by Intevel** [comment]
Yes, I thought it was an unbuild bug too. 
The current version is: 0.8.10

But I dont know when it was working last time :/ 
So yesterday at midday it worked. I dont know

**Comment by pi0** [comment]
Shall we close this if it fixes the issue?

**Comment by Intevel** [comment]
Yes it fixed, we can close this.

**Comment by Intevel** [comment]
Okay nevermind - Routes Folder isnt right
Is there no way to build everything in ` ./src/`
![image](https://user-images.githubusercontent.com/59223342/188598282-428015f5-970a-4ed2-9161-787c3f2cce1e.png)

**Comment by pi0** [comment]
mkdist items in stub mode are always as is. We cannot use jiti for them to change extension.

**Comment by Intevel** [comment]
Its not an mkdist item?

**Comment by pi0** [comment]
It is in mkdist mode. But in stub mode, unbuild makes a symlink for mkdist items. This way we can use live code changes from source project. If you need jiti stub, have to use rollup mode for entries.

**Comment by Intevel** [comment]
Is there no way to stub the complete TypeScript Code in `/src/` @pi0?

**Comment by Intevel** [comment]
@pi0 
![image](https://user-images.githubusercontent.com/59223342/188828373-8db44147-ecc4-4bea-b15b-41de9e59edb7.png)

Thats not right, when I stub the dist will copied in the src folder??

```
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
    // If entries is not provided, will be automatically inferred from package.json
    entries: [
        // default
        './src/index',
        './src/routes'
    
    ],

    outDir: 'dist',

    // Generates .d.ts declaration file
    declaration: false,
})
```
