### ISSUE TITLE
How to include auto-imported APIs in build?

### ISSUE THREAD

**Issue by chrisbbreuer** [unjs/unbuild#116]
Hi everyone,

This is not so much an issue but rather a question toward some direction:

Currently, I am auto-importing APIs via @antfu's [unplugin-auto-import](https://github.com/antfu/unplugin-auto-import), and I am looking to also include those auto-imported APIs into the build.

Is there a possibility to currently achieve this that I am not thinking about?

_As a minimal example, this is the file I am looking to build: https://github.com/ow3org/stacks/blob/main/functions/counter.ts#L2_

Thanks for this awesome tool!

**Comment by chrisbbreuer** [comment]
For auto compatibility with @antfu's plugin, I am thinking that we could check whether an `.eslintrc-auto-import.json` is present and then scan the output for whether any of those globals are present. If they are present, we could include the import into the build? 

What do you think @pi0? Is this something that would make sense as part of this package or would you rather leave this out?

**Comment by chrisbbreuer** [comment]
Or, theoretically, we could simply add a new hook to add to the imports and leave the application logic to the end user. That way, the codebase would stay more unopiniated while extending flexibility.

Would love to hear anyone's thoughts. Currently taking a stab at it 🙂

**Comment by andrew8088** [comment]
Running into this same problem with unbuild + unimport today! Any chance you have a solution @chrisbbreuer?
