### ISSUE TITLE
Subpath import is incorrect

### ISSUE THREAD

**Issue by danielroe** [unjs/unbuild#13]
https://github.com/unjs/unbuild/blob/f7c03e23a1f178267c895188040ddcacc032b153/src/builder/untyped.ts#L4

cf.: https://github.com/unjs/untyped/blob/main/package.json#L13-L15

We either need to fix here or add another export in `untyped` - cc @pi0

**Comment by pi0** [comment]
Using new `loder/babel` seems good idea. We can drop node <12 :)
