### ISSUE TITLE
Error when using `npm-check-updates` js api after build by `unbuild`

### ISSUE THREAD

**Issue by qmhc** [unjs/unbuild#132]
Related issue: https://github.com/raineorshine/npm-check-updates/issues/1204

Reproduction: https://github.com/qmhc/ncu-test

NCU author said it is an issue of unbuild, NCU works correctly as a module both in js and ts.

But I am not sure about this, currently I have used some packages and only found NCU will take errors.

**Comment by pi0** [comment]
~> #468
