### ISSUE TITLE
The `entries` option should allow globs

### ISSUE THREAD

**Issue by aleclarson** [unjs/unbuild#140]

**Comment by dwightjack** [comment]
I think it depends on the builder. `mkdist` already supports globs and the `pattern` option will be available once https://github.com/unjs/unbuild/pull/139 is merged and released. Example:

```ts
export default defineBuildConfig({
    entries: [
        {
            builder: 'mkdist',
            input: './src/package/components/',
            outDir: './build/components',
            pattern: '*.vue'
        },
    ],
})
```

The `input` option of the default `rollup` builder directly translates to Rollup's [input](https://rollupjs.org/guide/en/#input) option which does not natively support globs. The documentation there has an example using the `glob` library to create dynamic entries that I think could be used with unbuild as well.

I think the reason for not supporting globs is that, usually, you have a limited, known number of entry points in your library.
