### ISSUE TITLE
scss support?

### ISSUE THREAD

**Issue by amery** [unjs/unbuild#153]
is there an example about how to integrate scss on `build.config.ts`?

**Comment by amery** [comment]
I got a solution for `rollup`, but none for `mkdist` to distribute the source .scss files yet

```ts
import { defineBuildConfig } from "unbuild";
import { resolve } from "pathe";

import scss from "rollup-plugin-scss";

export default defineBuildConfig({
	entries: [
		{
			builder: "rollup",
			input: "./src/scss/mything.scss",
		},
	],

	hooks: {
		"rollup:options"(_ctx, options) {
			const plugin = scss({
				fileName: "mything.css",
				includePaths: [resolve(__dirname, "node_modules")],
			});

			if (options.plugins === undefined) {
				options.plugins = [plugin];
			} else if (Array.isArray(options.plugins)) {
				options.plugins.push(plugin);
			} else {
				options.plugins = [options.plugins, plugin];
			}
		},
	},
});
```
noisy... and it can be reduced assuming rollupOptions is always an Array as explained by @dwightjack but...

**Comment by dwightjack** [comment]
@amery looking at mkdist source code, there seems to be [basic support for sass](https://github.com/unjs/mkdist/blob/main/src/loaders/sass.ts). The loader matches files with `sass` or `scss` extension and transforms them to CSS. Anyway, I don't see any support for advanced customizations like resolve path.

**Comment by amery** [comment]
> @amery looking at mkdist source code, there seems to be [basic support for sass](https://github.com/unjs/mkdist/blob/main/src/loaders/sass.ts). The loader matches files with `sass` or `scss` extension and transforms them to CSS. Anyway, I don't see any support for advanced customizations like resolve path.

I expected `mkdist` to simply copy the files but it fails if an import doesn't resolve, understandably. I suppose I'll have to take it with them to add a mechanism to set the resolve path

**Comment by dwightjack** [comment]
I see. I think there isn't a way to achieve your goal with unbuild alone. Maybe you could use it with another tool to copy the files or use unbuild programmatically in a custom node script with something like [cpy](https://github.com/sindresorhus/cpy) like:

```js
// build.mjs
import { build as unbuild} from 'unbuild';
import cpy from 'cpy';

// build with unbuild
// '.' is the folder where you run the command
// unbuild reads the `unbuild.config.ts` file in that folder
await unbuild('.', false)

// copy files as-is
await cpy([ /* patterns here */])
```

and then run it from the root of your project

```
node ./build.mjs
```

**Comment by jd-solanki** [comment]
Que: https://discord.com/channels/473401852243869706/1050375232441036830

Anu solution: https://github.com/jd-solanki/anu/blob/main/packages/preset-theme-default/build.config.ts#L23

**Comment by pi0** [comment]
Sass files will be automatically transformed by `mkdist` builder (entries ending with `/`) file by file. 

For rollup, you might need a custom plugin and configuration of your choice.

We might also support Assets/Raw builder that copies without transform (#266)

**Comment by rr210** [comment]
> Que: https://discord.com/channels/473401852243869706/1050375232441036830
> 
> Anu solution: https://github.com/jd-solanki/anu/blob/main/packages/preset-theme-default/build.config.ts#L23

less support？
