### ISSUE TITLE
Since v1 - SyntaxError: The keyword 'interface' is reserved

### ISSUE THREAD

**Issue by deleonio** [unjs/unbuild#169]
### Environment

node 16
npm 8
pnpm 7
typescript 4.9

### Reproduction

build this

```ts
interface MyInterface {}
```

### Describe the bug

Error: SyntaxError: The keyword 'interface' is reserved

**Comment by dwightjack** [comment]
@deleonio could you please share your `build.config.ts` file?

**Comment by ModyQyW** [comment]
I am facing the same problem.

My `build.config.ts`

```ts
import { defineBuildConfig } from 'unbuild';

export default defineBuildConfig({
  entries: ['./src/index'],
  clean: true,
  declaration: true,
  rollup: {
    emitCJS: true,
    inlineDependencies: true,
    esbuild: {
      target: 'es2020',
    },
  },
});

```

The error occurs when I move `throttle-debounce` and `@types/throttle-debounce` from `dependencies` to `devDependencies` and run `unbuild`.

I use `throttle-debounce` like this.

```ts
export { debounce, throttle } from 'throttle-debounce';
```

**Comment by pi0** [comment]
If you are using a dependency in your project, please make sure it is either in `dependencies` or `peerDependencies` (and **NOT** `devDependencies) otherwise add it to the `externalDependencies` in `build.config`

**Comment by innocenzi** [comment]
@pi0 in this situation, shouldn't `throttle-debounce` just be inlined?
