### ISSUE TITLE
Error when building in stub mode

### ISSUE THREAD

**Issue by ohmree** [unjs/unbuild#182]
### Environment

```console
$ uname -srmov
Linux 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux
```
```console
$ node --version
v19.2.0
```
```console
$ pnpm list
Legend: production dependency, optional only, dev only

repro@0.0.0 /tmp/repro (PRIVATE)

dependencies:
@trpc/server 10.5.0
zod 3.20.2

devDependencies:
@antfu/eslint-config 0.34.0
@tsconfig/node18-strictest-esm 1.0.1
eslint 8.29.0
eslint-config-prettier 8.5.0
eslint-define-config 1.12.0
eslint-plugin-prettier 4.2.1
prettier 2.8.1
typescript 4.9.4
unbuild 1.0.2
```

### Reproduction

https://github.com/ohmree/unbuild-repro

### Describe the bug

When running `unbuild --stub` in the linked reproduction repo I get an vague error that looks like it comes from node's filesystem api.
The actual resulting files in `dist/` are partially generated and the ones that do get created seem to be working.

### Additional context

After doing some digging around using node's inspector and the chromium devtools I've come to the conclusion that the issue might have to do with the `pathe` package.
Additionally when the files in `dist/` get partially created the ones that are missing are from more intricate parts of the `package.json` `"exports"` field - namely subpath exports.

### Logs

```console
$ pnpm unbuild --stub
ℹ Automatically detected entries: src/index, src/routers, src/context [esm] [cjs] [dts]    17:26:16
ℹ Stubbing repro                                                                           17:26:16
Error building /tmp/repro: Error: EISDIR: illegal operation on a directory, read
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

**Comment by zoeyzhao19** [comment]
@ohmree ,as I found:
1. `unbuild` had inferred entry files successfully from the pkg file(`src/index, src/routers, src/context`).
2. then `unbuild` use  `JITI`  with esm resolution-algorithm and try to resolve entry files in stub mode 
```js
```

**Comment by zoeyzhao19** [comment]
@ohmree ,as I found: (Not necessarily accurate)

1. `unbuild` had inferred entry files successfully from the pkg file(src/index, src/routers, src/context),
2. then `unbuild` use `JITI` with **esm resolution-algorithm** and try to resolve entry files in stub mode,
```js
function tryResolve (id: string, rootDir: string = process.cwd()) {
  const _require = jiti(rootDir, { interopDefault: true, esmResolve: true });
  try {
    return _require.resolve(id);
  } catch (error: any) {
    if (error.code !== "MODULE_NOT_FOUND") {
      console.error(`Error trying import ${id} from ${rootDir}`, error);
    }
    return id;
  }
}
```
3. since you have a directory named `routers`, which is resolved firstly by [**esm resolution-algorithm**](https://nodejs.org/api/esm.html#resolution-algorithm). So the resolved result of your `src/routers` entry is not a writable file,
4. but I think it is not a good way have `routers.ts` and a routers folder at the same time, rename your routers folder maybe a better way.

**Comment by marrowleaves** [comment]
This can be achieved by manually defining the `entries` in `build.config.ts`, e.g

```
import { defineBuildConfig } from 'unbuild';

export default defineBuildConfig({
  entries: [{ input: './src/routers/index', name: 'routers' }],
  clean: true,
  declaration: true,
});

```

**Comment by pi0** [comment]
You might also configure jiti options for stub mode in next release: https://github.com/unjs/unbuild/pull/282

Please ping me to reopen if still having issues 🤞🏼
