### ISSUE TITLE
Could not find entrypoint for "bin" field in package.json

### ISSUE THREAD

**Issue by Plasticine-Yang** [unjs/unbuild#191]
### Environment

`unbuild.config.ts`

```ts

import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  entries: ['src/index.ts'],
  outDir: 'dist',
  clean: true,
  declaration: true,
  rollup: {
    emitCJS: true,
    cjsBridge: true,
  },
  failOnWarn: false,
})
```

`package.json`

```json
{
  "type": "module",
  "main": "./dist/index.cjs",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "require": "./dist/index.cjs",
      "import": "./dist/index.mjs",
      "types": "./dist/index.d.ts"
    }
  },
  "bin": {
    "plasticine-react": "./bin/plasticine-react.js"
  },
  "scripts": {
    "build": "unbuild"
  },
}
```

`bin/plasticine-react.js`

```js
#!/usr/bin/env node
import '../dist/index.mjs'
```

### Reproduction

```shell
git clone https://github.com/Plasticine-Yang/plasticine-react.git
pnpm i
pnpm -C packages/cli build
```

### Describe the bug

When I try to build a library with the "bin" field in package.json, unbuild will prompt that the bin entry cannot be found.

Even if I set failOnWarn to false, it will still exit with status code 1.

Can I help not detect the bin field? Because my bin field points to a js file imported into the packaged product, and is not generated by unbuild.

### Additional context

![image](https://user-images.githubusercontent.com/63829979/210291375-45273813-bdd9-4bff-82ec-a52581a68f78.png)

**Comment by zoeyzhao19** [comment]
rename your `unbuild.ts` to `build.config.ts`

**Comment by Plasticine-Yang** [comment]
> 

Thanks!

I didn't find that I wrote the name of the configuration file wrong. It's too bad! :(

**Comment by wulucxy** [comment]
@Plasticine-Yang  I still not work, how do you solve this。

it seems unbuild not recognize `bin field` in package.json

```
"bin": {
    "create-tars": "./bin/create-tars.js"
  },
```
