### ISSUE TITLE
support extending configuration

### ISSUE THREAD

**Issue by danielroe** [unjs/unbuild#195]
### Describe the feature

in a monorepo it would be nice to be able to have some common configuration (for example, a hook after build to copy licence/readme) that could be set at a higher level and 'inherited' when loading specific unbuild config

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
This is a good idea. By switching to C12 (https://github.com/unjs/unbuild/issues/94), we can support it out of the box for unbuild as well to extend build configuration.

**Comment by pi0** [comment]
Let's keep track via https://github.com/unjs/unbuild/issues/94 (trying to minimize open issues currently)
