### ISSUE TITLE
It's unreasonable to trigger `Inlined implicit external` warning when the related alias was configured.

### ISSUE THREAD

**Issue by Plasticine-Yang** [unjs/unbuild#201]
### Environment

Node.js version: v18.12.1

### Reproduction

https://github.com/Plasticine-Yang/plasticine-monitor

run `pnpm build:browser` can trigger the bug.

### Describe the bug

It will trigger `Inlined implicit external @/sdk` when I don't config the alias for `@`, which is reasonable.

However, the `@/sdk` is a path alias point to `packages/browser/src/sdk.ts`, it is not a dependency package.

> I also configured the paths option in tsconfig.json, but it is just for IDE and tsc to resolve the path, which is not related to the rollup under the unbuild.

So, it should be solved when I configure the alias `@` pointing to `packages/browser/src`, but it still trigger the `Inlined implicit external @/sdk` warning.

I'm not sure whether it is a bug or a feature. The issue can be closed if it is a feature.

### Additional context

The file imports a module with alias: `packages/browser/src/plugins/error-monitor-plugin/index.ts`:

```ts
import type { Plugin } from '@plasticine-monitor/core'

import { WebSDK } from '@/sdk'
import { monitorJSError } from './monitors/js-error'

/**
 * @description 监听运行时错误插件
 */
const errorMonitorPlugin = (): Plugin<WebSDK> => {
  return {
    install(webSDK) {
      monitorJSError(webSDK)
    },
  }
}

const __TEMP__ = WebSDK
console.log(__TEMP__)

export { errorMonitorPlugin }
```

The `@/sdk` points to `packages/browser/src/sdk.ts`.

`build.config.ts`

```ts
export default defineBuildConfig({
  entries: ['./src/index'],
  outDir: 'dist',
  clean: true,
  declaration: true,
  rollup: {
    emitCJS: true,
  },
  alias: {
    '@': resolve(__dirname, 'src'),
  },
})
```
![image](https://user-images.githubusercontent.com/63829979/212803900-01382d25-bd31-4eb5-a847-007090358d78.png)

**Comment by sechi747** [comment]
Same for me, have you resolved it?

**Comment by Plasticine-Yang** [comment]
> Same for me, have you resolved it?

Not yet. No one responded to me, I could only cancel the alias.

**Comment by sechi747** [comment]
> > Same for me, have you resolved it?
> 
> Not yet. No one responded to me, I could only cancel the alias.
I just add `failOnWarn: false` in build.config.ts, because the packaged files is correct. It just a warning not an error.

**Comment by NamesMT** [comment]
+1 simple aliases like ~/ for src/ also trigger "Inlined implicit external", this with the fact that alias breaks in stub mode means unbuild doesn't support alias at all.

**Comment by pi0** [comment]
It should not happen if aliases are configured. Please provide a minimal reproduction (ie stackblitz/codesandbox).

**Comment by NamesMT** [comment]
Hello @pi0, heres a reproduction link:  
https://codesandbox.io/p/github/NamesMT/starter-ts/draft/musing-albattani (run the reproduce script)

It happens using normal bundle mode and not with mkdist, alias is configured in both build.config.ts and tsconfig.json

**Comment by Plasticine-Yang** [comment]
> Same for me, have you resolved it?

I just replace ungit with tsup.

**Comment by gnclmorais** [comment]
I ran into the same issue… :/

**Comment by RIP21** [comment]
Even for simple aliases it won't work. Let say `@lib` alias to `lib` folder in case of `mkdist` doesn't work and stays `@lib/whatever` in the imports of the emitted files.

For anyone who looks for a workaround, the only one I figured is to use vite in lib mode with config like. It's slower in case of the first run (13-15 seconds for my lib) (but very reliable as it uses `tsc` to emit declarations) but subsequent if you use `vite build --watch` is 8-9x faster. So just 2-3 seconds for my project. 
```ts
// @ts-expect-error
import peerDepsExternal from 'rollup-plugin-peer-deps-external'
import type { LibraryFormats, UserConfig } from 'vite'
import dts from 'vite-plugin-dts'
import noBundle from 'vite-plugin-no-bundle'
import tsconfigPaths from 'vite-tsconfig-paths'
import react from '@vitejs/plugin-react-swc'

export default defineConfig({
  {
    plugins: [
      tsconfigPaths(),
      react(),
      dts({ include: ['lib'], insertTypesEntry: true }),
      noBundle({
        root: './lib',
      }),
    ],
    build: {
      minify: false,
      sourcemap: true,
      copyPublicDir: false,
      reportCompressedSize: false,
      lib: {
        entry: {
          index: resolve(__dirname, 'lib/index.ts')
        },
        formats: ["es"],
      },
      rollupOptions: {
        plugins: [
          peerDepsExternal({
            includeDependencies: true,
          }),
        ],
      },
    },
  }
})

```

**Comment by trandaison** [comment]
@sechi747 
> I just add failOnWarn: false in build.config.ts, because the packaged files are correct. It just a warning not an error.

Can you explain a little bit more? I am facing with this problem with https://github.com/nuxt/module-builder (which is built on top of unbuild), but there is no documents that show how/where to set `failOnWarn: false`

**Comment by trandaison** [comment]
@sechi747 My current workaround solution:
```ts
// build.config.ts

import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  failOnWarn: false,
});
```

**Comment by HigherOrderLogic** [comment]
Hi @pi0, is this issue on the roadmap? These false positive warnings are very annoying to work with.

**Comment by olets** [comment]
The same thing happens with package.json subpath imports https://nodejs.org/api/packages.html#subpath-imports

Here's a minimal reproduction https://stackblitz.com/edit/vitejs-vite-kwryzn?file=src%2Findex.ts

Lmk if I should open a new issue.

**Comment by xsjcTony** [comment]
Indeed it's happening for my project as well. https://github.com/xsjcTony/remark-magic-link
This should definitely be fixed as it forces you to set `failOnWarn: false` which is not safe.

**Comment by xsjcTony** [comment]
There's seems to be the same issue before, and it's fixed https://github.com/unjs/unbuild/issues/383. 
Checked the release note, maybe try `v3.0.0-rc2`?
https://github.com/unjs/unbuild/releases/tag/v3.0.0-rc.2

**Comment by wangjue666** [comment]
> 之前似乎也有同样的问题，已修复#383。 查看了发布说明，也许可以试试`v3.0.0-rc2`？ https://github.com/unjs/unbuild/releases/tag/v3.0.0-rc.2

It's useful to me

**Comment by pi0** [comment]
#384 available in 3.x fixes issue with aliases that were wrongly detected as externals. 

#351 aims to also auto add package namage/subpaths itself as they are valid aliases in ESM resolution.

In case you had other issues in v3, please feel free to report a new issue 🙏🏼
