### ISSUE TITLE
How to add 'global.d.ts' to build file?

### ISSUE THREAD

**Issue by laoer536** [unjs/unbuild#204]
### Environment

  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.48.2",
    "@typescript-eslint/parser": "^5.48.2",
    "@vitest/coverage-c8": "^0.27.2",
    "eslint": "^8.32.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "prettier": "^2.8.3",
    "standard-version": "^9.5.0",
    "typescript": "^4.9.4",
    "unbuild": "^1.1.1",
    "vite": "^4.0.4",
    "vitest": "^0.27.2"
  }

build.config.ts:
import { defineBuildConfig } from "unbuild";
export default defineBuildConfig({
    entries: ["./src/index"],
    declaration: true,
    clean: true,
    failOnWarn: false,
    rollup: {
        emitCJS: true,
        esbuild: {
            minify: true,
        }
    }
});

### Reproduction

no

### Describe the bug

src/types/test.d.ts
```ts
interface TestSome{
    name:string
}
```

src/is.ts
```ts
export function test(data:TestSome){
  console.log(data)
}
```

build->dist/index.d.ts
```ts
declare function test(data: TestSome): void;  // Cannot find name 'TestSome'.
```
How to resolve? Thanks a lot! 😩

**Comment by zoeyzhao19** [comment]
@laoer536  use `mkdist` builder, try change your `build.config.ts`  entries opion to
```js
entries: ['./src/index', './src/types/']
```

**Comment by itancc** [comment]
> @laoer536 use `mkdist` builder, try change your `build.config.ts` entries option to
> 
> ```js
> entries: ['./src/index', './src/types/']
> ```
> 
> entry ended with `/` means use mkdist builder

it doesn't seem to work for .d.ts

**Comment by sadeghbarati** [comment]
Why you don't use `.ts` for types? Maybe that type is unused that's why it's not present in the build file


BTW, You can do it with unbuild [`rollup:dts:build`](https://github.com/unjs/unbuild/blob/8e6962eb8ae651dbd7ec9484e71439c9648a7b53/src/types.ts#L134) hook

```ts
import { defineBuildConfig } from 'unbuild'
import { promises as fsp } from 'fs'
import { join, resolve } from 'pathe'

export default defineBuildConfig({
  entries: ['src/index'],
  declaration: true,
  hooks: {
    'rollup:dts:build': async (ctx, bundle) => {
      const globalDts = await fsp.readFile(resolve(join(ctx.options.rootDir, 'global.d.ts')), 'utf8')
      
      bundle.write({
        dir: ctx.options.outDir || 'dist',
        format: 'esm',
        exports: 'named',
        banner: globalDts,
        // or
        // footer: globalDts 
      })
    }
  },
  rollup: {
    emitCJS: true
  }
})
```

**Comment by laoer536** [comment]
> Why you don't use `.ts` for types? Maybe that type is unused that's why it's not present in the build file
> 
> 
> BTW, You can do it with unbuild [`rollup:dts:build`](https://github.com/unjs/unbuild/blob/8e6962eb8ae651dbd7ec9484e71439c9648a7b53/src/types.ts#L134) hook
> 
> ```ts
> import { defineBuildConfig } from 'unbuild'
> import { promises as fsp } from 'fs'
> import { join, resolve } from 'pathe'
> 
> export default defineBuildConfig({
>   entries: ['src/index'],
>   declaration: true,
>   hooks: {
>     'rollup:dts:build': async (ctx, bundle) => {
>       const globalDts = await fsp.readFile(resolve(join(ctx.options.rootDir, 'global.d.ts')), 'utf8')
>       
>       bundle.write({
>         dir: ctx.options.outDir || 'dist',
>         format: 'esm',
>         exports: 'named',
>         banner: globalDts,
>         // or
>         // footer: globalDts 
>       })
>     }
>   },
>   rollup: {
>     emitCJS: true
>   }
> })
> ```

OK, thanks a lot.
