### ISSUE TITLE
Mixed js + ts code generates broken type declarations

### ISSUE THREAD

**Issue by KernelDeimos** [unjs/unbuild#205]
### Environment

```
$ node -v
v18.7.0
$ cat package-lock.json | grep "unbuild" | head -n 1
        "unbuild": "^1.1.1"
```

### Reproduction

I've created [this repository](https://gitea.coherentconstructs.com/cc-contrib/npm_unbuild_2023-01-19) to reproduce the issue.

The `index.ts` file is generated from a kind of roll-your-own static autoloader - I've left that out for the sake of simplicity. It exists because my package doesn't have a logical "entry point", rather it's a collection of small utilities.

### Describe the bug

After running `unbuild` with my config in the linked repository, I get this output:

```javascript
class TestClass {
  something() {
    console.log("TestClass");
  }
}

declare class AnotherClass {
    something(): string;
}

interface I_testpkg_deeper {
    "AnotherClass": new (...args: any[]) => AnotherClass;
}
interface I_testpkg {
    "TestClass": new (...args: any[]) => TestClass;
    "deeper": I_testpkg_deeper;
}
declare const _default: {
    testpkg: I_testpkg;
};

export { _default as default };
```

When TestClass is outputted I get:
```
class TestClass {
  something() {
    console.log("TestClass");
  }
}
```

when I really expect either this class to be ignored, or to get something like the following:
```
declare class TestClass {
  something(...args: any[]): any
}
```

**Comment by zoeyzhao19** [comment]
@KernelDeimos  add `tsconfig.json` simplely like
```js
{
  "compilerOptions": {
    "allowJs": true
  },
  "include": ["src"]
}

```
would output

![image](https://user-images.githubusercontent.com/70888488/217222881-7ba17503-d83c-4425-a24d-7eac85cc0eb2.png)

Is this what you want?

**Comment by pi0** [comment]
(please ping to reopen if you still have issues)
