### ISSUE TITLE
CJS Shim as official plugin

### ISSUE THREAD

**Issue by tada5hi** [unjs/unbuild#207]
### Describe the feature

Hey @pi0,

I really like your simple cjs shim implementation for esm output bundles and would like to convert that to an official rollup plugin. 
If that would be ok for you, I would be happy about a transfer from your side. I'm also happy to do the transfer if you prefer.

Greetings
Peter

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Happy you found it helpful! Of course, feel free to extract and create a standalone roll-up plugin 💯  (i prefer to keep unbuild deps minimum will keep using inlined implementation. feel free to backport and improvements if you found any 👍🏼 )

**Comment by tada5hi** [comment]
Glad to hear :blush:. I will do that. Thank you for the quick feedback :v: :relaxed:

**Comment by pi0** [comment]
Update:

https://github.com/rollup/plugins/pull/1415

https://github.com/rollup/plugins/tree/master/packages/esm-shim

Thanks @tada5hi ❤️
