### ISSUE TITLE
Improve docs and comparisons

### ISSUE THREAD

**Issue by D4RKAR117** [unjs/unbuild#210]
### Describe the feature

I think that this project is great, but lack some docs around config reference, the inline docs for each config option, comparisons and use cases between other tools like Vite or tsup where the line becomes blur sometimes at the time to choose or prefer unbuild.

This could help for adoption over the tooling small projects or over large organizations (which is my case for example), where the only guide publicly aware of the goodies of this project it's for example this [blog post](https://antfu.me/posts/publish-esm-and-cjs#bundling)

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for the heads up. I fully agree with you about improving docs. Let's track via #219
