### ISSUE TITLE
Unfriendly unbuild stub in some case

### ISSUE THREAD

**Issue by zoeyzhao19** [unjs/unbuild#211]
### Environment

System:
  OS: Windows 10 10.0.22000
  Memory: 4.19 GB / 23.74 GB
npmPackages:
  unbuild: ^1.1.1 => 1.1.1

### Reproduction

1. git clone [demo repo](https://github.com/zoeyzhao19/cli-unbuild-stub-issue)
2. pnpm install 
3. pnpm dev
4. then link cli with `npm link `
5. excute `clitest dev` to test the cli
6. open `http://127.0.0.1:5173` in the browser

### Describe the bug

  I am using `unbuild` to develop my cli tool and everything go well in `unbuild` build model. But when I use `unbuild --stub` , `npm link` and run cli command `clitest dev`, open my browser, then the program is broken. 
![image](https://user-images.githubusercontent.com/70888488/217164894-a6d00c04-4c72-4a0d-9333-0a7854071e1f.png)
  My cli tool is going to create a dev server through vite like this: 
```js
cli.command('dev', 'start dev server').action(async () => {
  console.log('start dev server');
  createDevServer();
});
```
```js
export async function createDevServer() {
  const serevr = await createServer({
    plugins: [pluginIndexHtml()],
  });
  await serevr.listen();
  serevr.printUrls();
}
```
```js
function pluginIndexHtml(): Plugin {
  return {
    name: 'index-html',
    apply: 'serve',
    configureServer(server) {
      return () => {
        server.middlewares.use(async (req, res, next) => {
          let html = await fs.readFileSync(htmlPath, 'utf-8');
         // this broken the program in unbuild stub
          html = await server.transformIndexHtml(
            req.url!,
            html,
            req.originalUrl
          );
          res.setHeader('Content-Type', 'text/html');
          res.end(html);
        });
      };
    },
  };
}
```
I found that when run into `server.transformIndexHtml`, it will finally excute the `traverseHtml` method in vite below
```js
const require = __cjs_createRequire(import.meta.url);
async function traverseHtml(html, filePath, visitor) {
    // lazy load compiler
    const { parse } = await import('./dep-98d07f71.js');
   ...
}
```
As `JITI` use babel to transform esm like `import` to `require`,  and hijack native require to `createJITI()`, and code above maybe transform internally to something like
```js
const _require2 = (0, _nodeModule.createRequire)(xxx);
async function traverseHtml(html, filePath, visitor) {
    // lazy load compiler
    const { parse } = await Promise.resolve().then(() => _require2('./dep-98d07f71.js'));
   ...
}
```
So jiti require target file use `_require2` but not `require/createJITI()`, `_require2` is more like a native require, which cause:
![image](https://user-images.githubusercontent.com/70888488/217164894-a6d00c04-4c72-4a0d-9333-0a7854071e1f.png)

I try to manually add extra babel plugin in `dist/cli.mjs` and it worked
```js
import jiti from 'file:///E:/gitpro/cli-unbuild-stub-issue/node_modules/.pnpm/jiti@1.16.2/node_modules/jiti/lib/index.js';
import dynamicImport from '@babel/plugin-proposal-dynamic-import';

/** @type {import("E:/gitpro/cli-unbuild-stub-issue/src/cli")} */
const _module = jiti(null, {
  interopDefault: true,
  esmResolve: true,
  transformOptions: {
    babel: {
      plugins: [dynamicImport],
    },
  },
})('E:/gitpro/cli-unbuild-stub-issue/src/cli.ts');

export default _module;
```
and internally JITI transform vite code to
```js
const _require2 = (0, _nodeModule.createRequire)(xxx);
async function traverseHtml(html, filePath, visitor) {
    // lazy load compiler
   const { parse } = await Promise.resolve().then(() => _interopRequireWildcard(require('./dep-98d07f71.js')));
   ...
}
```
So is it a possible way for `unbuild` to expose the JITI options for user case or maybe I should go to `JITI` for more solution?

**Comment by pi0** [comment]
In next version, you can customize jiti options using `stubOptions.jiti`. Thanks for the idea!
