### ISSUE TITLE
Register Custom Builder

### ISSUE THREAD

**Issue by cpreston321** [unjs/unbuild#212]
### Describe the feature

I would like the option to register a customer builder so we can extend unbuild at our ability for certain use cases. This gives us the flexibility without updating the core unbuild package. 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi can you elaborate more? How it would be different than providing hooks to extend?

**Comment by cpreston321** [comment]
Hey @pi0! I guess my thought behind it was since the current builders are `rollup`, `untyped` and `mkdist`. It does give me the options to extend those builders through hooks. I was thinking more a way for if someone wanted to create a builder without it being baked in the package which is making will make the efforts harder depending on release cycles.  Furthermore this could bring more developers to come up with there own alternatives that could possibly adopt for the future. 

## Pros

-  Developers have more flexibility to publish there builder and extend config from hooks once registered. 
-  Developers can come up with opinionated builders that others might choice over what is built in within `unbuild`.
-  Could possibly move `untyped` & `mkdist` to the main repo and then will have a flexible system with builders and hooks.
- Easier to maintain for both developer and unbuild maintainer. 

I can't think of any cons unless, the initial the thought was to keep more inline within unjs org and let unbuild drive all the builders. Which is totally fine. I was just thinking out loud, because who knows how much cool things would be leveraging `unbuild` to build for them. 

Thanks,
Christian
