### ISSUE TITLE
cannot use kebab-case keys from `.json` file default exports

### ISSUE THREAD

**Issue by alexzhang1030** [unjs/unbuild#217]
### Environment

stackblitz
unbuild:  ^1.1.1
node: 16.14.2

### Reproduction

https://stackblitz.com/edit/node-z61fts?file=index.js

### Describe the bug

When import a kabab-case field from json file. 

The result after the build is incorrect.

Please see `reproduction` and execute `npm run build`, and see `dist/index.js.mjs`.

I think this is an upstream error from `rollup`. But I cannot reproduce it by using rollup.

**Comment by zoeyzhao19** [comment]
@alexzhang1030 , it is due to `@rollup/plugin-json` try to make identitier legal through
```js
const makeLegalIdentifier = function makeLegalIdentifier(str) {
    let identifier = str
        .replace(/-(\w)/g, (_, letter) => letter.toUpperCase())
        .replace(/[^$_a-zA-Z0-9]/g, '_');
    if (/\d/.test(identifier[0]) || forbiddenIdentifiers.has(identifier)) {
        identifier = `_${identifier}`;
    }
    return identifier || '_';
};
```
So it replace `something-idk` to `somethingIdk`, that's why the named export code in the bundle file doesn't contain the kebab-case field. Related to [here](https://github.com/rollup/plugins/issues/1437)

**Comment by alexzhang1030** [comment]
> @alexzhang1030 , it is due to `@rollup/plugin-json` try to make identitier legal through
> 
> ```js
> const makeLegalIdentifier = function makeLegalIdentifier(str) {
>     let identifier = str
>         .replace(/-(\w)/g, (_, letter) => letter.toUpperCase())
>         .replace(/[^$_a-zA-Z0-9]/g, '_');
>     if (/\d/.test(identifier[0]) || forbiddenIdentifiers.has(identifier)) {
>         identifier = `_${identifier}`;
>     }
>     return identifier || '_';
> };
> ```
> 
> So it replace `something-idk` to `somethingIdk`, that's why the named export code in the bundle file doesn't contain the kebab-case field. Related to [here](https://github.com/rollup/plugins/issues/1437)

I think so, let's track this issue.
