### ISSUE TITLE
Improve build option docs

### ISSUE THREAD

**Issue by ederzz** [unjs/unbuild#219]
### Describe the feature

Could u add some docs has more details with build options?
In readme, I could find options in [types](https://github.com/unjs/unbuild/blob/main/src/types.ts), but don't get their meaning.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Linking https://github.com/unjs/unbuild/issues/210 and https://antfu.me/posts/publish-esm-and-cjs#bundling

**Comment by D4RKAR117** [comment]
Would be very useful also the usage of rollup plugins with in unbuild, It's pretty tricky and hidden if you're new to the package

**Comment by Barbapapazes** [comment]
> ### Describe the feature
> Could u add some docs has more details with build options? In readme, I could find options in [types](https://github.com/unjs/unbuild/blob/main/src/types.ts?rgh-link-date=2023-02-17T02%3A57%3A12Z), but don't get their meaning.
> 
> ### Additional information
> * [ ]  Would you be willing to help implement this feature?

Hello, thanks for reporting this! I will work on it!

**Comment by RSS1102** [comment]
May I ask why this `document` has not been pushed forward? As mentioned above, there are many configurations that cannot understand its meaning. I don't even know what functions he can have. 🤔

---
I can provide assistance for this, if you are willing.

**Comment by Barbapapazes** [comment]
Hey, what do you mean by `document`?

**Comment by RSS1102** [comment]
What are the configurations in `buildonfig` and what is the purpose of each configuration.

As he said:
>Could u add some docs has more details with build options?
In readme, I could find options in [types](https://github.com/unjs/unbuild/blob/main/src/types.ts), but don't get their meaning.

**Comment by RSS1102** [comment]
🤔 @Barbapapazes so can I provide a PR to build this document? i want to try it.

 ---
Perhaps using vitepress?

**Comment by Barbapapazes** [comment]
> 🤔 @Barbapapazes so can I provide a PR to build this document? i want to try it.
> 
> Perhaps using vitepress?

The first thing to do is to add some comments to document there types. Actually, there is no need for a full documentation.

**Comment by RSS1102** [comment]
> > 🤔 @Barbapapazes so can I provide a PR to build this document? i want to try it.
> > Perhaps using vitepress?
> 
> The first thing to do is to add some comments to document there types. Actually, there is no need for a full documentation.

#363 But it seems a bit messy for the code files.
Perhaps there should be some descriptions of `packson` or `build.config.ts`
