### ISSUE TITLE
SyntaxError: Unexpected token .d.ts Build failed for vite

### ISSUE THREAD

**Issue by yanquanfahei** [unjs/unbuild#225]
### Environment

- node: v16.14.2
- vite: ^4.1.4
- unbuild: ^1.1.2
- typescript: ^4.9.3

### Reproduction

[stackblitz](https://stackblitz.com/edit/vitejs-vite-jo1hdt?file=package.json,src%2Findex.ts,unbuild.config.ts&terminal=dev)

### Describe the bug

SyntaxError: Unexpected token (3:12) in /home/projects/vitejs-vite-jo1hdt/node_modules/vite/dist/node/index.d.ts

**Comment by zoeyzhao19** [comment]
@yanquanfahei,  by the way, you have the wrong config file name, your config file does noe work. It is exactly `build.config.ts`, and try to add 
```js
export default defineBuildConfig({
  entries: ['src/index'],
  declaration: true,
  externals: ['vite']
});

```
in your config file,
or move `vite` to `dependencies` filed in your package.json, It may work.

**Comment by yanquanfahei** [comment]
> 

Thank you for your help. It works 😊

**Comment by zoeyzhao19** [comment]
@yanquanfahei , happy to help you.  Although it worked, maybe it's also some restriction of unbuild.  If I insisted on a internal deps of  `vite`, then it would always come to the error. I think it was because `unbuild` does not handle the `d.ts` file before it comes to the rollup commonjs plugin.

**Comment by QC2168** [comment]
Good! It working
