### ISSUE TITLE
Support `externals` with regex

### ISSUE THREAD

**Issue by tjx666** [unjs/unbuild#227]
### Describe the feature

like esbuild packages options: https://esbuild.github.io/getting-started/#bundling-for-node:~:text=You%20can%20exclude%20all%20of%20your%20dependencies%20from%20the%20bundle%20by%20setting%20packages%20to%20external%3A

```shell
esbuild app.jsx --bundle --platform=node --packages=external
```

For now, the externals option doesn't support pass regexp.
If support pass regexp, I may config to：

```
export default {
  entries: [
    './src/index'
  ],
  externals: /^[^.]/
}
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Supported via https://github.com/unjs/unbuild/pull/145
