### ISSUE TITLE
add a build preset for web containers

### ISSUE THREAD

**Issue by cpreston321** [unjs/unbuild#240]
### Describe the feature

This preset would target a folder that would create a json file of all the contents of each file within a JSON file to easily start a web container with it. I'm not for sure if this is the right spot for it but it would be cool to see that you can just change the preset and it will build a web-container file that you can ingest using the API: https://webcontainers.io/ 

Structure like so (Pulled straight from docs example:)

## Start up index script: 

```js
import { WebContainer, FileSystemTree } from '@webcontainer/api';
import { projectFiles } from './project-files.ts';

async function main() {
  // First we boot a WebContainer
  const webcontainer = await WebContainer.boot();
  
  // After booting the container we copy all of our project files
  // into the container's file system
  await webcontainer.mount(projectFiles);
    
  // Once the files have been mounted, we install the project's
  // dependencies by spawning `npm install`
  const install = await webcontainer.spawn('npm', ['i']);
  
  await install.exit;
    
  // Once all dependencies have been installed, we can spawn `npm`
  // to run the `dev` script from the project's `package.json`
  await webcontainer.spawn('npm', ['run', 'dev']);
}
```

## Content JSON structure.
 
```js
export const projectFiles = {
  myProject: {
    directory: {
      'package.json': {
        file: {
          contents: '...',
        }
      },
      'index.js': {
        file: {
          contents: '...',
        }
      },
    }
  }
};
```

Maybe it's a separate package.  I am just thinking out loud. Maybe we can just discuss it but it only sounds right since unbuild is a unified builder.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Do you have some examples of projects would be built based on such project?

Also are you thinking to mainly generate the json output from unbuild? 

We might alternatively target it as a nitro preset too but would love to hear more about your vision how we can integrate with stackblitz format..

**Comment by pi0** [comment]
Exciting stuff and ideas! Shall we start with an experimental repo to see how it looks like? Feel free to ping me in discord  pi0#6582 to continue this there are some relevant ideas could be nice to brainstorm together how to join them.

**Comment by pi0** [comment]
closing as there seems not much demand for this (and we might move this to next gen tooling later)
