### ISSUE TITLE
Support Array BuildConfig

### ISSUE THREAD

**Issue by sadeghbarati** [unjs/unbuild#245]
### Describe the feature

Refrence: 
- [Rollup](https://github.com/rollup/rollup/blob/0bcf0a672ac087ff2eb88fbba45ec62389a4f45f/src/rollup/types.d.ts#L952)
- [tsup](https://github.com/egoist/tsup/blob/322cb772d8ddb73fbb6192199c29c3917c659ce0/src/index.ts#L30)

Currently unbuild `^1.2.0` [defineBuildConfig](https://github.com/unjs/unbuild/blob/f7e614bbcbd2471d58db7d3ace3fafec7d9b8465/src/types.ts#L180) support one `BuildConfig` not `BuildConfig[]`
`unbuild` expose an API called `build` to do things in a programmatic way,
 But I prefer using `build.config.ts` file with unbuild cli instead of creating a script file like `build.mjs`

### Additional information
I want to apply different configs per entry

#### Simple example

<details>

```ts
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig([
  {
    entries: 'src/index',
    replace: {
      __DEV__: `(process.env.NODE_ENV === 'development')`
    }
    rollup: {
      emitCJS: true
    }
  },
  {
    entries: 'src/index',
    outDir: 'dist/min',
    replace: {
      __DEV__: JSON.stringify(process.env.NODE_ENV === 'development')
    }
    rollup: {
      emitCJS: true,
      esbuild: {
        minify: true
      }
    }
  }
])
```

</details>

#### Advanced example
[Pinia rollup.config](https://github.com/vuejs/pinia/blob/v2/rollup.config.mjs)

I like unbuild `jiti`[^1] and `hooks` features, and I wonder how to convert that config to unbuild.config

- [ ] Would you be willing to help implement this feature?

[^1]: jitti feature is not compatible with monorepos

**Comment by patzick** [comment]
I need the same thing so prepared PR related to this issue :)
