### ISSUE TITLE
using unbuild --stub support alias config in build.config.ts

### ISSUE THREAD

**Issue by xuemanchi** [unjs/unbuild#272]
### Describe the feature

When I am using `unbuild --stub`, unbuild will use `jiti mode`. But if I have already configured `alias` in ·build.config.ts`, the alias does not work. And If i execute file, will report error: 

```
Error: Cannot find module '@/foo'
Require stack:
- code\packages\shared\src\color.ts
 - code/node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:241025
 - code/node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:243309
 - code/packages/shared/src/color.ts:4:13
 - code/node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:245784
 - code/packages/shared/src/index.ts:3:14
 - code/node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:245784
```

So I want to support this feature

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by zoeyzhao19** [comment]
Did you work on a monorepo and just to want to import a package specified in your workspace ?

**Comment by pi0** [comment]
Aliases for stub entries will be supported in next release (#283) 👍🏼
