### ISSUE TITLE
No description on npmjs

### ISSUE THREAD

**Issue by MrAmericanMike** [unjs/unbuild#274]
### Describe the feature

The package page at npmjs provides no description.

https://www.npmjs.com/package/unbuild

I'm guessing it's because it's not been informed of the readme location on the repository. Not sure where npmjs takes this from exactly, but I'm guessing it's from the package.json file?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. Would you please explain which part is missing in npm webpage so i can direct what to fix.

<img width="1281" alt="image" src="https://github.com/unjs/unbuild/assets/5158436/37ba430d-f235-47b5-87c2-981618c423c2">

**Comment by MrAmericanMike** [comment]
Ohh yes, I was talking about that. I'm guessing something on my end then must be messing things out, I see the description now.

Sorry for the inconvenience.
