### ISSUE TITLE
A file might be imported multiple times when using stubs on Windows

### ISSUE THREAD

**Issue by ah-dc** [unjs/unbuild#290]
### Environment

Windows

### Reproduction

I created one on stackblitz but it is Linux.

https://stackblitz.com/edit/stackblitz-starters-m3lfbv1

### Describe the bug

Windows support `\` and `/` as path separator, so a file might be imported more than once with different path on Windows, for example `C:\foo.ts` and `C:/foo.ts`. It causes problems when this file has side effects.

### Additional context

Normalizing paths might solve this issue

**Comment by ah-dc** [comment]
Maybe I should report it in jiti repository

**Comment by pi0** [comment]
Hi. Yes, if the issue only happens on windows with **stub** mode, it makes sense to be moved into jiti. Would you mind to create one there?

**Comment by ah-dc** [comment]
> Hi. Yes, if the issue only happens on windows with **stub** mode, it makes sense to be moved into jiti. Would you mind to create one there?

ok

**Comment by pi0** [comment]
https://github.com/unjs/jiti/issues/151
