### ISSUE TITLE
In the stub mode, mkdistBuild can support a similar effect like jiti.

### ISSUE THREAD

**Issue by 1514100951** [unjs/unbuild#299]
### Describe the feature

I am now starting with stup when compiling the entire directory, and the files in that directory cannot have a jiti like effect

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by 1514100951** [comment]
The main purpose is to implement this similar functionality in monorepo.
![image](https://github.com/unjs/unbuild/assets/45170904/9c580fe5-be85-4e19-b8f3-080f4563cd8a)
![image](https://github.com/unjs/unbuild/assets/45170904/10fcc10a-bca2-4e07-bec4-e3facda8db83)
In order to achieve this effect, I made a method, I do not know if there is a better way, That's how it's done
![image](https://github.com/unjs/unbuild/assets/45170904/9514ed77-648f-4a08-bb00-f459c1405786)

**Comment by pi0** [comment]
mkdist stubs are meant to be used with compatible runtime (bun, deno and latest node with native typescript support) or bundlers (vite, rollup). jiti support is only for bundled rollup.

**Comment by productdevbook** [comment]
but it gives an error because it does not find .mjs in the import in these playground areas. How do we avoid this. package.json is set according to mjs.
