### ISSUE TITLE
cannot build to cjs using mkdist

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/unbuild#311]
Hello,

I was experimenting with unbuild and I encounter an issue.

Is it possible (if recommanded) to build to esm and cjs at the same time using `mkdist` like with rollup?

**Comment by Barbapapazes** [comment]
I expect to have 

```
    ├── vite.cjs
    ├── vite.d.cts
    ├── vite.d.mts
    ├── vite.d.ts
    ├── vite.mjs
    ├── webpack.cjs
    ├── webpack.d.cts
    ├── webpack.d.mts
    ├── webpack.d.ts
    └── webpack.mjs
```

but I only got

```
├── vite.d.ts
├── vite.mjs
├── webpack.d.ts
└── webpack.mjs
```

**Comment by joshmeads** [comment]
Here was my work around:

```ts
function dualOutput(
  config: Omit<MkdistBuildEntry, "builder" | "format">
): BuildEntry[] {
  return [
    {
      builder: "mkdist",
      format: "esm",
      ...config,
      pattern: "**/!(*.stories).{js,jsx,ts,tsx}",
    },
    {
      builder: "mkdist",
      format: "cjs",
      ...config,
      pattern: "**/!(*.stories).{js,jsx,ts,tsx}",
    },
  ];
}
```
```ts
export default defineBuildConfig({
  entries: [
    "./src/index",
    ...dualOutput({
      input: "./src/components/Bits/",
      outDir: "./dist/bits",
    }),
```

**Comment by Barbapapazes** [comment]
> Here was my work around for now, just a snippet I use in most the configs:
> 
> ```ts
> function dualOutput(
>   config: Omit<MkdistBuildEntry, "builder" | "format">
> ): BuildEntry[] {
>   return [
>     {
>       builder: "mkdist",
>       format: "esm",
>       ...config,
>       pattern: "**/!(*.stories).{js,jsx,ts,tsx}",
>     },
>     {
>       builder: "mkdist",
>       format: "cjs",
>       ...config,
>       pattern: "**/!(*.stories).{js,jsx,ts,tsx}",
>     },
>   ];
> }
> ```
> 
> ```ts
> export default defineBuildConfig({
>   entries: [
>     "./src/index",
>     ...dualOutput({
>       input: "./src/components/Bits/",
>       outDir: "./dist/bits",
>     }),
> ```

Yeah, I'm also using this way but, since there is a way to generate both with the rollup preset, I was hoping to do the same way for mkdist!

**Comment by pi0** [comment]
Moving docs to https://github.com/unjs/unbuild/issues/398
