### ISSUE TITLE
declaration not work

### ISSUE THREAD

**Issue by hzhoup** [unjs/unbuild#313]
### Environment

node: v16.20.0

"unbuild": "^2.0.0"

### Reproduction

non

### Describe the bug

I set declaration `false` in the setting file

```js
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  clean: true,
  entries: ['src/index.js'],
  declaration: false,
  rollup: {
    emitCJS: true
  }
})
```

run `unbuild --stud`: 
![image](https://github.com/unjs/unbuild/assets/109516832/e9b04f06-8848-410d-95d5-d375a719a7ba)

**Comment by xiaoxiangmoe** [comment]
@hzhoup hi, I create a bugfix for it.
