### ISSUE TITLE
ouput file

### ISSUE THREAD

**Issue by hzhoup** [unjs/unbuild#316]
### Environment

"unbuild": "^2.0.0"
node: 16.20.0

### Reproduction

non

### Describe the bug

没有根据 package.json 的字段生成相应文件，后缀应该是 `.js` & `.cjs`

![image](https://github.com/unjs/unbuild/assets/109516832/f53515c2-cf4e-4c95-bdf3-4bb1ebccbdec)

![image](https://github.com/unjs/unbuild/assets/109516832/baf14789-8c03-4573-b12f-88343ef05c1a)

**Comment by hzhoup** [comment]
package.json 有配置 `"type": "module"`

**Comment by hzhoup** [comment]
`build.config.js`
```js
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  entries: ['src/index'],
  clean: true,
  declaration: true,
  rollup: {
    emitCJS: true
  }
})
```

**Comment by hzhoup** [comment]
`main` 和 `module` 字段写反了，请忽略...修正后表现一样

**Comment by pi0** [comment]
Hi. sorry the question is unclear please reopen with reproduction
