### ISSUE TITLE
cannot do the dead code elimination the vitest in-source testing code 

### ISSUE THREAD

**Issue by kazupon** [unjs/unbuild#319]
### package.json
```json
{
  "name": "unbuild-repro-1",
  "private": true,
  "devDependencies": {
    "bun-types": "latest",
    "typescript": "^5.0.0",
    "unbuild": "^2.0.0",
    "vitest": "^0.34.5"
  },
  "module": "./dist/index.mjs",
  "type": "module",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.mjs",
      "require": "./dist/index.cjs"
    },
    "./dist/*": "./dist/*",
    "./package.json": "./package.json"
  },
  "scripts": {
    "build": "unbuild",
    "test": "vitest run"
  }
}
```

### Node.js version

```sh
$ node -v
v18.16.1
```

### Reproduction

https://github.com/kazupon/unbuild-repro-1

### Describe the bug

According to the vitest documentation, the test code can do Dead Code Elimination during production build by specifying the replace option `'import.meta.vitest': undefined`.
However, this is not possible. 

https://vitest.dev/guide/in-source.html#production-build
### 

### work-around
As workaround for until fixing, we can avoid this by doing the following

```ts
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  // something options ...
  // 

  hooks: {
    'rollup:options': (ctx, options) => {
      ;(options.plugins as any).push({
        name: 'workaround-strip-in-source-test',
        transform(code: string, id: string) {
          return {
            code: code.replace(/import.meta.vitest/g, 'false'),
            map: null,
          }
        },
      })
    },
  },
})
```

**Comment by kazupon** [comment]
I think dead code elimination  correctly is `'import.meta.vitest': String(false)`,  not `'import.meta.vitest': undefined` :)

**Comment by antfu** [comment]
Hey @kazupon

In the docs it's `'import.meta.vitest': 'undefined'` not `'import.meta.vitest': undefined` 👀

Using `'false'` would do the same, unless you want to use something like 

```ts
import.meta.vitest?.it('test', ({ expect }) => {})
```

In which `'undefined'` would work better.

Either way, I consider it a non-issue of unbuild.

**Comment by kazupon** [comment]
Thank you for quick reply!

Oh, I saw wrong it… 😅 
Sorry to open a noisy issue. 🙇 

This is not an issue. I'll close.
