### ISSUE TITLE
MJS / pass through copy on input

### ISSUE THREAD

**Issue by kaleidawave** [unjs/unbuild#324]
### Describe the feature

I have several files that I want built to ESM and CJS. Additionally there is an input **that uses top level await**.

This causes a problem because it cannot generate a CJS build with TLA 🙃.

If I move the TLA files to specific files, is there a way to just copy those items through and not generate `.cjs` editions?

My [current package.json](https://github.com/kaleidawave/ezno/blob/random-fixes-54/src/js-cli-and-library/package.json) for reference

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. It seems you have module exports with `require` condition. And top level export is not supported for CommonJS format.

If you remove them + `"emitCJS": true` line + main/bin field to use `.mjs` package builds:

<img width="946" alt="image" src="https://github.com/unjs/unbuild/assets/5158436/bbda5ff7-3122-4d90-a1c2-08c3926a3ada">


You can also use a CJS proxy entry (it only allows async function exports)

Example: https://github.com/unjs/ofetch/blob/v1.0.0/cjs/index.cjs

Let me know if you like a PR and if it was your question.

**Comment by kaleidawave** [comment]
Awesome, that seems to have worked! 🎉 

Another contributor setup the build so was unsure what the options did
