### ISSUE TITLE
Generate TSX with Solid factory

### ISSUE THREAD

**Issue by SokuRitszZ** [unjs/unbuild#325]
### Describe the feature

I'm trying to build my package what is using solid-js.

![image](https://github.com/unjs/unbuild/assets/84608230/95212fd0-0d1f-41d5-bc19-71f2deb57868)

but the result is:

![image](https://github.com/unjs/unbuild/assets/84608230/ce1243b8-c9bf-451f-b42a-c17dee7605d4)

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. You can use TSConfig to change jsxFactory settings generating solid output. If you can share you repo i can help better :)

**Comment by SokuRitszZ** [comment]
> Hi. You can use TSConfig to change jsxFactory settings generating solid output. If you can share you repo i can help better :)

I tried to set `jsxFactory: createComponent` & add `/** @jsx createComponent */` at the begining of `jsx` file, there is no error but it generated code that
![image](https://github.com/unjs/unbuild/assets/84608230/458cd4dd-0a3a-4e81-bbb3-091e4ff4acc0)
it seems to be very similar with how `React.createElement` create dom. It should be the result like that 
![image](https://github.com/unjs/unbuild/assets/84608230/01ae86f3-9248-4a05-adcb-9d4a585b9985)

Here is the repo of my code: https://github.com/SokuRitszZ/monorepo-test, and the path is `packages/reversi-solid-renderer`. Thanks for your help!

I apologize for my poor English and open source experience :(

**Comment by 17359898647** [comment]
Have you solved it yet

**Comment by pi0** [comment]
A nice reference by @crutchcorn here for anyone wondering how: https://github.com/cmgriffing/shiki-magic-move/pull/3

(closing to track from #398 as docs)
