### ISSUE TITLE
How to build dependencies?

### ISSUE THREAD

**Issue by eivmosn** [unjs/unbuild#329]
### Describe the feature

build the dependencies in the final output file, but now it will generate like "export { xxxx } from 'xxxx'", how it can bundle the source code from dependencies?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Can you please share your repo?

**Comment by eivmosn** [comment]
> Can you please share your repo?

sure u can find repo from my profile which is named utils. I have install throttle-debounce in my package.json file and i want build it in the output files

**Comment by eivmosn** [comment]
> > Can you please share your repo?
> 
> sure u can find repo from my profile which is named utils. I have install throttle-debounce in my package.json file and i want build it in the output files

in src/index.ts i  have write code like  "export { debounce, throttle } from 'throttle-debounce'"
