### ISSUE TITLE
Import assertions are lost

### ISSUE THREAD

**Issue by JohnCampionJr** [unjs/unbuild#331]
### Environment

Node 18

### Reproduction

Put a JSON import with an assertion to a TS file and run unbuild

### Describe the bug

`import pkg from 'npm-package/package.json' assert { type: "json" }`

loses the assert and becomes

`import pkg from 'npm-package/package.json'`

### Additional context

Note that package.json is actually exported by the package I'm using.   It works fine otherwise.

ESBuild leaves it alone as expected in ESM formats.

**Comment by JohnCampionJr** [comment]
This is a low priority and can be closed if you don't want to fix; I found an alternate way to accomplish what I was looking to do :)

**Comment by pi0** [comment]
checking against latest v3, it is preserved in rollup output.
