### ISSUE TITLE
Add package subpath exports/imports to external by default

### ISSUE THREAD

**Issue by pi0** [unjs/unbuild#351]
(also https://github.com/unjs/unbuild/issues/467)

Would be worth to add package name (and subpaths) to externals by default

**Comment by olets** [comment]
pi0 I know you already know this, but repeating here in case it helps others untangle the linked issues:

This would resolve the bug of subpath imports triggering an external imports warning reproduced in https://stackblitz.com/edit/unbuild-301-subpath-import-false-positive-warning
