### ISSUE TITLE
rollup-plugin-esbuild has import issue which affects 0.5.10 to latest

### ISSUE THREAD

**Issue by mvdschee** [unjs/unbuild#36]
`rollup-plugin-esbuild` had an issue with import for es-module-lexer: https://github.com/egoist/rollup-plugin-esbuild/issues/325

this affects all fresh installs from Unbuild:

please upgrade to `"rollup-plugin-esbuild": "4.8.2"` to resolve this issue

**Comment by mvdschee** [comment]
in the background it uses version `4.8.2` so this is not as critical, but it might be nice to update the package either way.

**Comment by 1018715564** [comment]
Yes, I also found this problem yesterday, I am going to mention pr to solve it, just to see your issue
