### ISSUE TITLE
Support `automd` builder

### ISSUE THREAD

**Issue by cpreston321** [unjs/unbuild#369]
Could be handy if it was a part of the package. So that you can just run unbuild.

**Comment by pi0** [comment]
Would be nice for unbuild integration 💯 

(i was thinking of adding integration for `changelogen` too syncing readme when making a new release -- for example for adding new utils only when released)

**Comment by pi0** [comment]
Hi. Thinking more probably adopting automd in release related tooling would be better idea. unbuild can probably integrated with hooks.

If you still like to do it in unbuild please ping to reopen btw 👍🏼
