### ISSUE TITLE
Correct CJS bundling

### ISSUE THREAD

**Issue by levchak0910** [unjs/unbuild#374]
### Describe the feature

**Default exports** are not correctly exported from CJS files

When creating a package using `unbuild` CJS exports cause [Masquerading as ESM error](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseESM.md) ([example from my lib](https://github.com/levchak0910/css-media-splitter/actions/runs/8031004764/job/21938902948))

Several libraries need to run a post-build script to change the source of `.cjs` files

Affected libs:

- https://github.com/levchak0910/css-media-splitter/blob/main/scripts/post-build-dist.ts
- https://github.com/antfu/vite-plugin-inspect/blob/main/scripts/postbuild.ts
- https://github.com/vitejs/vite/blob/main/scripts/patchCJS.ts
- https://github.com/onebay/vite-plugin-imp/blob/main/scripts/patchCJS.ts

other can be found too: https://github.com/search?q=patchCjs&type=code

Is it possible to fix this behavior within the library?

Huge thanks to @userquin for helping to figure it out

---

And thanks for awesome tool )

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
I believe the CJS generated type issues are related to #457 lets track from single place there.
