### ISSUE TITLE
More details about the option `inlineDependencies`

### ISSUE THREAD

**Issue by s3xysteak** [unjs/unbuild#376]
### Describe the change

I had a build error :  `Inlined implicit external`. And I google it and found [a unocss dev issue](https://github.com/unocss/unocss/issues/1696), which have the similar problem as mine. In the end of the issue it said a commit fixed it:
```ts
rollup: {
  inlineDependencies: true,
},
```
I tried it on my project and it fixed it too.
I thought that is a rollup option but I cannot find it. So I think that is a new options of `unbuild`. But it do not provide any comments.
Could you provide more details about it? Thank you!

### URLs

https://github.com/unjs/unbuild/blob/bfb4a348421826ad48072ca1cf70973e6caa5b1d/src/types.ts#L51

### Additional information

- [X] Would you be willing to help?

**Comment by edorgeville** [comment]
For anyone else experiencing the same warning, create a `build.config.ts` file at the root of your project with the following content:
```typescript
import { defineBuildConfig } from "unbuild"

export default defineBuildConfig({
  rollup: {
    inlineDependencies: true
  }
})
``` 
I agree that explaning what this config does would be beneficial 😅

**Comment by s3xysteak** [comment]
> For anyone else experiencing the same warning, create a `build.config.ts` file at the root of your project with the following content:
> 
> ```ts
> import { defineBuildConfig } from "unbuild"
> 
> export default defineBuildConfig({
>   rollup: {
>     inlineDependencies: true
>   }
> })
> ```
> 
> I agree that explaining what this config does would be beneficial 😅

Are you using alias? I just found out that it missed the case of using an alias, which is one of the reasons that led to this issue. I think maybe I should open a bug issue to talk about it.

**Comment by edorgeville** [comment]
@s3xysteak I wasn't!  
Turns out I had runtime dependencies that were listed under `devDependencies` instead of `dependencies` in my `package.json`. This triggered the default inlining of those during the build.

**Comment by pi0** [comment]
Thanks for explaining @edorgeville. @s3xysteak moving this to https://github.com/unjs/unbuild/issues/398 for single tracker.
