### ISSUE TITLE
jsdoc

### ISSUE THREAD

**Issue by coderbaozi** [unjs/unbuild#386]
### Describe the feature

Please tell me how to configure it so that jsdoc can be retained during packaging.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by coderbaozi** [comment]
config
export default defineBuildConfig({
  entries: [
    'src/index',
    'src/cli/index',
  ],
  declaration: true,
  clean: true,
  rollup: {
    emitCJS: true,
  },
})

**Comment by dwightjack** [comment]
@coderbaozi because unbuild uses esbuild for bundling, I don't think there a global way to retain JSDoc comments. 

What you can do, is to add the `@preserve` tag to those comment blocks you want to keep. For example:

```js
/**
 * A log Function
 * @param  {...any} args Arguments to log
 * @returns {void}
 * @preserve
 */
export const log = (...args) => {
  console.log(...args);
};
```
