### ISSUE TITLE
Unbuild: Dynamic imports

### ISSUE THREAD

**Issue by nethriis** [unjs/unbuild#395]
### Discussed in https://github.com/unjs/community/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **nethriis** May  4, 2024</sup>
Hi, does anyone know how to dynamically import TypeScript files with `unbuild` in ESM? I have this code:

```ts
export const command = {
  ping: () => import(findPath('ping')).then(m => m.default || m)
}
```

However, during the prepack with `unbuild`, I don't see a 'chunks' folder, and consequently there's an import issue for this file.</div>

**Comment by pi0** [comment]
Mirror from https://github.com/unjs/unstorage/issues/440

> nethriis: When the argument of import is a static string like './commands/ping' the chunks folder is generated on prepack and everything works well but with a variable, in my case findPath('ping') the chuncks folder is not generated

**Comment by pi0** [comment]
Hi. You need to pass statically analazable paths to both static and dynamic imports this way rollup can properly resolve them during build and bundle/make chunks.

It should be something like `import('./path/to/ping.ts'`) for example.
