### ISSUE TITLE
"a" unified vs "an" unified

### ISSUE THREAD

**Issue by Zizico2** [unjs/unbuild#42]
I'm fully aware I am beeing very (very) pedantic, but even though "unified" starts with a vowel, phonetically it starts with the "y" sound, so it should be preceded by an "a" not an "an". Feel free to close this issue if you don't care c:

**Comment by danielroe** [comment]
closed in https://github.com/unjs/unbuild/commit/f8f7ce21bd2d19a1360fe5374501b8f8d6155289
