### ISSUE TITLE
how to relative tsconfig  when import a module that belongs to  `exports`

### ISSUE THREAD

**Issue by buquan** [unjs/unbuild#421]
### Environment

node 20 ts5+

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zbxug8?file=src%2Findex.ts,package.json,src%2Fadd.ts,src%2Fsub.ts,build.config.ts,tsconfig.json

### Describe the bug

ts error `add is not a module when ` import * as addObj from './add';

**Comment by prisis** [comment]
Sorry, this has nothing to do with unbuild, please check https://stackoverflow.com/questions/32805559/typescript-es6-import-module-file-is-not-a-module-error
