### ISSUE TITLE
'unbuild' vue ts component to npm

### ISSUE THREAD

**Issue by kugatsu765** [unjs/unbuild#44]
Hello, 

I have a question. i try to build a vue 3 components with unbuild to publish on private npm repository. But i fail each time i try ^^. 

I build correctly some ts function. So i thinks unbuild is ok. But when i try to export vue component from my index.ts. it fails. 

config  unbuild : 

```ts
import { defineBuildConfig } from 'unbuild'
export default defineBuildConfig({
    entries: [
        './src/index',
        { input: './src/components/', outDir: './dist/components' },
    ],
    declaration: true,
    cjsBridge: true
})
```

package.json
```json
{
  "name": "@test/buttons-vue3",
  "version": "1.0.0",
  "description": "Buttons components for vue3",
  "main": "src/index.ts",
  "scripts": {
    "build:lib": "npx unbuild"
  },
  "keywords": ["vue3", "vuejs", "button"],
  "author": "Romain GABEL",
  "license": "ISC",
  "peerDependencies": {
    "vue": "^3.2.26"
  },
  "devDependencies": {
    "@vue/compiler-sfc": "^3.2.26",
    "unbuild": "^0.5.13",
    "vue-tsc": "^0.28.10"
  }
}
```

and my index.ts
```ts
import ButtonApp from "./components/ButtonApp.vue";
export { ButtonApp }
export * from './fn'
```

I don't know what dependencies i have to import or what i miss in this simple config file. If someone could help =) 

Thank you for your work @antfu !

**Comment by kugatsu765** [comment]
Sorry i missed to print the error.
<img width="1111" alt="Capture d’écran 2022-01-27 à 15 10 16" src="https://user-images.githubusercontent.com/41836255/151375321-d294b02c-dfb3-49c2-99a4-0690cebc3406.png">

**Comment by kugatsu765** [comment]
Hello Again, i reproduce the issue in a small repository link here : https://github.com/kugatsu765/ti-ui-ts-issue-unbuild

Thanks for watching

**Comment by kugatsu765** [comment]
Hy, after a lot of test and rebuild from the begining i could make it work in most case. 

- [x] vuejs as js
- [x] vuejs as ts
- [x] import from index.ts if the index file is in /components
- [ ] vuejs as ts with `script setup` 😢

**Comment by wobsoriano** [comment]
did you get it to working?

**Comment by itsmnthn** [comment]
@kugatsu765 can you please share the solution
