### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by aleclarson** [unjs/unbuild#47]
How do I enable sourcemaps?

**Comment by theniceangel** [comment]
Yeah, it seems that sourcemap is broken

**Comment by SuperchupuDev** [comment]
@pi0 any chance we can get a fix for source maps? right now the `sourcemap` esbuild option doesn't generate them. looking forward to it

**Comment by zoeyzhao19** [comment]
@pi0  Since we cannot find any other option for sourcemap support for now. So can we just simplely respect `esbuild sourcemap` option. #192

**Comment by pi0** [comment]
Hi. I have moved it to #236 to track progress and move to the top.
