### ISSUE TITLE
mkdist ignores src files

### ISSUE THREAD

**Issue by xsjcTony** [unjs/unbuild#472]
### Environment

`Node.js`: `v20.18.0`
`unbuild`: ✅`v3.0.0-rc.11` / ❌`v3.0.0`

### Reproduction

https://github.com/xsjcTony/remark-magic-link/blob/main/package.json

### Describe the bug

This is the config  I'm using, however it works well (see screenshot for output) in `v3.0.0-rc.11`, but not in `v3.0.0` (as well as `v3.1.0`).
No idea why.
```ts
entries: [
  'src/index',
  { input: 'src', outDir: '.', pattern: ['**/*.css'], builder: 'mkdist', loaders: ['postcss'] },
],
```
![Snipaste_2024-12-29_01-24-25](https://github.com/user-attachments/assets/a9723ec9-a690-43ef-91e3-6359d46e8903)

### Additional context

It may because of the upgrade of `mkdist` to `v2`, I've tried to dig into it, but unfortunately I can't find anything.

**Comment by pi0** [comment]
Thanks for the report. this issue comes from mkdist since we migrated from globby to tinyglobby which does not support githinore natively. 

Here is a current workaround:

```js
    { input: 'src', outDir: '.', pattern: ['**/*.css'], builder: 'mkdist', loaders: ['postcss'],
      // @ts-expect-error unbuild type issue
      // TODO: remove after https://github.com/unjs/mkdist/pull/279
      globOptions: { ignore: [] } },
```

**Comment by pi0** [comment]
Fixed in https://github.com/unjs/mkdist/releases/tag/v2.2.0

(you can use `pnpm upgrade unbuild mkdist` to make sure `mkdist@2.2.0`+ is installed)
