### ISSUE TITLE
How to Customize Change File Suffix

### ISSUE THREAD

**Issue by seho-dev** [unjs/unbuild#50]
.mjs - > .js
.cjs -> .cjs

or

.mjs - > ${name}.esm.js
.cjs - > ${name}.cjs.js

Because when I introduced the plugin with the test project, there was an error
`Can't import the named export 'useRequestSign' from non EcmaScript module (only default export is available)                                    friendly-errors 13:15:54`

**Comment by pi0** [comment]
Please consider using standard `.mjs`/`.cjs` extensions when possible. They are natively supported by node.
