### ISSUE TITLE
Place files in separate folders

### ISSUE THREAD

**Issue by IanVS** [unjs/unbuild#51]
I'm proposing to add unbuild to a storybook package, but their convention is to place the outputs into different folders, like:

```
dist/cjs/index.js
dist/esm/index.js
```

And actually, what I want is:

```
dist/cjs/index.cjs
dist/esm/index.mjs
```

Is that possible?  I can't tell from looking at the names of the options.

**Comment by pi0** [comment]
Hi. In next version, you can actually configure entries to go to the subpaths (https://github.com/unjs/unbuild/pull/280) by using `./src/esm/index.*`. 

Please let me know to reopen if you had a different question 👍🏼
