### ISSUE TITLE
Reduce package install size

### ISSUE THREAD

**Issue by ydcjeff** [unjs/unbuild#53]
Currently `unbuild`'s install size is around 90MB which is huge. https://packagephobia.com/result?p=unbuild

And I found `typescript` is on dependencies.

https://github.com/unjs/unbuild/blob/e710503cda58a2691a6ed04abe91c346dae66d21/package.json#L51

`typescript` alone is around 60MB. https://packagephobia.com/result?p=typescript

Can we make `typescript` as peer dependency?

**Comment by pi0** [comment]
Hi. Typescript is an (optional) peer dependency now https://github.com/unjs/unbuild/commit/f31c6a4cf13d08c04b45fbf9c5651c3d93317ec2
