### ISSUE TITLE
Get error `Module '"vue"' has no exported member 'Component'` when unbuild with pnpm

### ISSUE THREAD

**Issue by aliuq** [unjs/unbuild#54]
Hi
I used pnpm to run build script, it gots `src/index.ts(1,15): error TS2305: Module '"vue"' has no exported member 'Component'.`
used npm and yarn are all building works, it seems the issue's reason of pnpm

debug long time…………

I found the issue is relationed with `declaration: true` config, if **declaration** value is **false**, it will build pass, but lost ***.d.ts** file

can you please help me to analyze it

Thank you.

here is a demo [repo](https://github.com/liuqian1996/test-unbuild-with-pnpm.git)

**index.ts**

```ts
import type { Component } from 'vue'

export function Demo(App: Component) {
  return App
}
```

**build.config.ts**

```ts
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  entries: [
    { input: 'src/index', name: 'index' },
  ],
  clean: true,
  declaration: true,
  externals: [
    'vue',
  ],
  rollup: {
    emitCJS: true,
  },
})
```
**tsconfig.json**

```json
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "es2020",
    "lib": [
      "ESNext",
      "DOM"
    ],
    "esModuleInterop": true,
    "strict": true,
    "strictNullChecks": true,
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "skipLibCheck": true
  },
  "exclude": [
    "**/dist",
    "**/node_modules",
    "**/test"
  ]
}

```

Error info

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/11707934/157436099-5e5bb957-a240-489b-9c87-715afc5be2ee.png">

**Comment by action-hong** [comment]
same problem

**Comment by aliuq** [comment]
> same problem

You can add `.npmrc` file on your project. refrenced to [vite-ssg](https://github.com/antfu/vite-ssg/blob/main/.npmrc)

**.npmrc**
```ini
shamefully-hoist = true
ignore-workspace-root-check = true
```

**Comment by action-hong** [comment]
it works  thanks 

> > same problem
> 
> You can add `.npmrc` file on your project. refrenced to [vite-ssg](https://github.com/antfu/vite-ssg/blob/main/.npmrc)
> 
> **.npmrc**
> 
> ```ini
> shamefully-hoist = true
> ignore-workspace-root-check = true
> ```

it works,  thank you

**Comment by danielroe** [comment]
This should be resolved in https://github.com/unjs/unbuild/pull/57 in the next release.

**Comment by aliuq** [comment]
I test on `v0.7.2`, it works correct
