### ISSUE TITLE
Support new react-jsx transform

### ISSUE THREAD

**Issue by llc1123** [unjs/unbuild#78]
For now, unbuild generates `React.createElement` on jsx, and the new jsx transform has been introduced for [more than a year](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html).

Is it possible to support the new jsx transform in unbuild?

**Comment by pi0** [comment]
JSX/TSX support is added in latest mkdist/unbuild as default

**Comment by timofei-iatsenko** [comment]
@pi0 well, that's still a case. Esbuild is triggered without `jsx: 'automatic',` option and it causes mismatch in what typescript is checking and what is really produced.
