### ISSUE TITLE
JSX or TSX is not compiled

### ISSUE THREAD

**Issue by zguiyang** [unjs/unbuild#91]
Hi, I'm having a packaging problem,.tsx is not compiled, do I need to do additional configuration or is there a reason for this

<img width="831" alt="image" src="https://user-images.githubusercontent.com/24975063/176660714-ecbebe99-73e3-4c44-b216-e93464ddc477.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/24975063/176660853-c406c17b-02d8-435e-a2be-19466e4a8dcc.png">

**Comment by dwightjack** [comment]
The `mkdist` builder does not support JSX or TSX compilation. I am not sure if the `rollup` builder supports it either 🤔

**Comment by pi0** [comment]
TSX support for mkdist added  by https://github.com/unjs/mkdist/pull/71
