### ISSUE TITLE
Better Documentation for Configuration Options

### ISSUE THREAD

**Issue by uchihamalolan** [unjs/unbuild#99]
### Problem
Currently only reference to configuration options available is link to the [types file](https://github.com/unjs/unbuild/blob/main/src/types.ts).
This is not really helpful for someone who's relatively new to bundling libraries in typescript etc...

### Solution
A proper documentation somewhere indicating what each property in the configuration object is for and possible values and when and why to use them etc... (maybe with some examples)

**Comment by pi0** [comment]
I fully agree. Let's track it from one place ~> https://github.com/unjs/unbuild/issues/219
